### ISSUE TITLE
Headless mode?

### ISSUE THREAD

**Issue by magick93** [rbi/trading4j#1]
Hello

Is it possible to run trading4j and mt4 in headless mode?

**Comment by rbi** [comment]
The trading4j server has no GUI so there is no problem with running it headless. I never tried to run MetaTrader 4 in headless mode. You should check at there website. If it can run any expert advisors in headless mode the trading4j expert advisor should work too.

What I've done is to run MetaTrader on a Linux VM using wine and Xvnc. This is not really headless but it did at least not require a physical screen.

**Comment by magick93** [comment]
Thanks @rbi 

Do you run MT4 in a docker container?

It is possible to start MT4 from the command line, and pass in a parameter to make it run in headless mode - but I dont recall what this parameter is. I will look into it further and let you know.

**Comment by rbi** [comment]
I did not try that but I think there should be no problem. I've run Xvnc and novnc in a docker container to create a Desktop I could access in a browser so MetaTrader should run there too. If there is a MT4 headless mode it should be even easier to run in docker.
